# This file contains the ports to expose
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: uaa-ports
spec:
  ports:
  - name: uaa-ssl
    port: 2793
    targetPort: uaa-ssl
  externalIPs :
  - 192.168.77.77
  selector:
    skiff-role-name: uaa
