#!/bin/bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

cd "$GIT_ROOT"
. ${GIT_ROOT}/.envrc
fissile build packages --stemcell ${FISSILE_STEMCELL}
fissile build images   --stemcell ${FISSILE_STEMCELL}
