#!/bin/bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

cd "$GIT_ROOT"
. ${GIT_ROOT}/.envrc
fissile build kube -k kube/ --use-memory-limits=false \
	    -D $(echo env/*.env | tr ' ' ',')
