#!/usr/bin/env bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
cd "${GIT_ROOT}"
source .envrc

ENV_FILES="$(echo env/*.env)"

CREATE_HELM_CHART=false
KUBE_OUTPUT_DIR=kube

if [ "${1:-}" = "helm" ]; then
    CREATE_HELM_CHART=true
    KUBE_OUTPUT_DIR=helm
    ENV_FILES=env/certs.env
fi

rm -rf ${KUBE_OUTPUT_DIR}

# TODO: We currently skip memory limits for development purposes
fissile build kube \
    --kube-output-dir="${KUBE_OUTPUT_DIR}" \
    --defaults-file="$(echo "${ENV_FILES}" | tr ' ' ,)" \
    --use-memory-limits=false \
    --create-helm-chart=${CREATE_HELM_CHART} \
    --chart-file=Chart.yaml
