#!/bin/bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. "${GIT_ROOT}/make/include/registry"

cd "$GIT_ROOT"
. ${GIT_ROOT}/.envrc
fissile build kube \
    -k kube/ \
    --use-memory-limits=false \
    --docker-registry "${IMAGE_REGISTRY}" \
    --docker-organization "${IMAGE_ORG}" \
    --repository "${IMAGE_PREFIX}" \
    -D $(echo env/*.env | tr ' ' ',')
