#!/usr/bin/env bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
cd "${GIT_ROOT}"
source .envrc

if [ -z "${APP_VERSION:-}" ]; then
  echo "APP_VERSION is not set"
  exit 1
fi

CREATE_HELM_CHART=false
BUILD_TARGET=kube

if [ "${1:-}" = "helm" ]; then
    CREATE_HELM_CHART=true
    BUILD_TARGET=helm
fi

rm -rf "${BUILD_TARGET}"

fissile build "${BUILD_TARGET}" \
    --output-dir="${BUILD_TARGET}"

if [ "${BUILD_TARGET}" = "helm" ]; then
    chart_name_suffix=""
    if [[ $FISSILE_STEMCELL =~ ^.*fissile-stemcell-opensuse.*$ ]] ; then
      chart_name_suffix="-opensuse"
    fi

    cat > "${BUILD_TARGET}/Chart.yaml" << EOF
apiVersion: ${APP_VERSION}
description: A Helm chart for SUSE UAA
name: uaa${chart_name_suffix}
version: ${GIT_TAG}
EOF
fi
