#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

cd "$GIT_ROOT"
. "${GIT_ROOT}/.envrc"

BOSH_IMAGES=${BOSH_IMAGES:-$(fissile show image --docker-registry "${UAA_IMAGE_REGISTRY}" --docker-organization "${UAA_IMAGE_ORG}" -p "${UAA_IMAGE_PREFIX}")}

for image in ${BOSH_IMAGES}; do
    # Redirect docker stdout to avoid polluting logfiles with progressbar characters
    docker push "${image}" > /dev/null
done
