#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

cd "$GIT_ROOT"

RUBY_VERSION=2.3.1 \
    ${GIT_ROOT}/bin/create-release.sh  src/cf-mysql-release  cf-mysql

${GIT_ROOT}/bin/create-release.sh  src/uaa-release  uaa
${GIT_ROOT}/bin/create-release.sh  src/hcf-release  hcf
