#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

cd "$GIT_ROOT"
bosh create release --dir src/cf-mysql-release --force --name cf-mysql
bosh create release --dir src/uaa-release --force --name uaa
bosh create release --dir src/hcf-release --force --name hcf
