#!/usr/bin/env bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
NAMESPACE="uaa"

has_namespace() {
    kubectl get namespace --output=name "${NAMESPACE}" >/dev/null 2>/dev/null
}

stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run start

stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run::namespace start
if has_namespace ; then
    kubectl delete namespace "${NAMESPACE}"
fi

printf "Waiting for namespace %s to be deleted...\n" "${NAMESPACE}"
while has_namespace ; do
    sleep 1
done

kubectl create namespace "${NAMESPACE}"
stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run::namespace end

stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run::create start

kubectl get storageclass persistent 2>/dev/null || {
    perl -p -e 's@storage.k8s.io/v1beta1@storage.k8s.io/v1@g' \
        "${GIT_ROOT}/kube-test/storage-class-host-path.yml" | \
    kubectl create -f -
}

DOMAIN=${DOMAIN:-}
DEFAULTS_ENV=container-host-files/etc/scf/config/env/defaults.env

if test -n "${DOMAIN}"; then
    TMP="$(mktemp -d)"
    cp "${DEFAULTS_ENV}" "${TMP}"
    # shellcheck disable=SC2064
    trap "rm -rf ${TMP}" EXIT
    DEFAULTS_ENV="${TMP}/$(basename "${DEFAULTS_ENV}")"
    sed -i "s/^DOMAIN=.*/DOMAIN=${DOMAIN}/" "${DEFAULTS_ENV}"
fi

source "${DEFAULTS_ENV}"

helm install helm \
     --name "${NAMESPACE}" \
     --namespace "${NAMESPACE}" \
     --set "env.DOMAIN=${DOMAIN}" \
     --set "secrets.UAA_ADMIN_CLIENT_SECRET=${UAA_ADMIN_CLIENT_SECRET}" \
     --set "kube.external_ips[0]=$(dig +short "${DOMAIN}")" \
     "$@"

stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run::create end

stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run 'done'
