#!/usr/bin/env bash

# Upgrade a running UAA using the current chart in
# src/uaa-fissile-release/helm. Assumes that only one revision is
# currently running. If more than one runs the last per helm's sorting
# order is chosen. (See **)

set -o errexit -o nounset

NAMESPACE="uaa"

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
cd "${GIT_ROOT}"

# Argument? (**)
RELEASE=${NAMESPACE}
echo Upgrading ${NAMESPACE} release \"${RELEASE}\" ...

stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run start
stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run::upgrade start

DOMAIN=${DOMAIN:-}
DEFAULTS_ENV=container-host-files/etc/scf/config/env/defaults.env

if test -n "${DOMAIN}"; then
    TMP="$(mktemp -d)"
    cp "${DEFAULTS_ENV}" "${TMP}"
    # shellcheck disable=SC2064
    trap "rm -rf ${TMP}" EXIT
    DEFAULTS_ENV="${TMP}/$(basename "${DEFAULTS_ENV}")"
    sed -i "s/^DOMAIN=.*/DOMAIN=${DOMAIN}/" "${DEFAULTS_ENV}"
fi

source "${DEFAULTS_ENV}"

helm upgrade ${RELEASE} helm \
     --namespace "${NAMESPACE}" \
     --set "env.DOMAIN=${DOMAIN}" \
     --set "secrets.UAA_ADMIN_CLIENT_SECRET=${UAA_ADMIN_CLIENT_SECRET}" \
     --set "kube.external_ips[0]=$(dig +short "${DOMAIN}")" \
     "$@"

stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run::upgrade end
stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run 'done'
