#!/usr/bin/env bash

# Upgrade a running UAA using the current chart in
# src/uaa-fissile-release/helm. Assumes that only one revision is
# currently running. If more than one runs the last per helm's sorting
# order is chosen. (See **)

set -o errexit -o nounset

NAMESPACE="uaa"

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
cd "${GIT_ROOT}"

# Argument? (**)
RELEASE=${NAMESPACE}
echo Upgrading ${NAMESPACE} release \"${RELEASE}\" ...

stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run start
stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run::upgrade start

DOMAIN=${DOMAIN:-cf-dev.io}

helm_args=(
    --namespace "${NAMESPACE}"
    --values "../../bin/settings.yaml"
    --set "env.DOMAIN=${DOMAIN}"
)

if [ -n "${INGRESS_CONTROLLER:-}" ]; then
    helm_args+=(
        --set "ingress.enabled=true"
        --set "ingress.annotations.kubernetes\.io\/ingress\.class=${INGRESS_CONTROLLER}"
        --set "env.UAA_PUBLIC_PORT=443"
    )
else
    helm_args+=(
        --set "kube.external_ips[0]=$(getent hosts "${DOMAIN}" | awk 'NR=1{print $1}')"
    )
fi

: "${UAA_CHART:="${GIT_ROOT}/helm"}"

echo helm upgrade "${RELEASE}" "${UAA_CHART}" "${helm_args[@]}" "$@"

helm upgrade "${RELEASE}" "${UAA_CHART}" "${helm_args[@]}" "$@"

stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run::upgrade end
stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run 'done'
