#!/usr/bin/env bash

# Upgrade a running UAA using the current chart in
# src/uaa-fissile-release/helm. Assumes that only one revision is
# currently running. If more than one runs the last per helm's sorting
# order is chosen. (See **)

set -o errexit -o nounset

NAMESPACE="uaa"

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
cd "${GIT_ROOT}"

# Argument? (**)
RELEASE=${NAMESPACE}
echo Upgrading ${NAMESPACE} release \"${RELEASE}\" ...

stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run start
stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run::upgrade start

DOMAIN=${DOMAIN:-cf-dev.io}

helm upgrade ${RELEASE} helm \
     --namespace "${NAMESPACE}" \
     --values "../../bin/settings.yaml" \
     --set "env.DOMAIN=${DOMAIN}" \
     --set "kube.external_ips[0]=$(getent hosts "${DOMAIN}" | awk 'NR=1{print $1}')" \
     "$@"

stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run::upgrade end
stampy "${GIT_ROOT}/uaa_metrics.csv" "$0" make-run 'done'
